name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-cuda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Jimver/cuda-toolkit@v0.2.30
      id: cuda-toolkit
      with:
        cuda: '13.1.0'
    - name: Build (CUDA)
      run: cargo build --release --features cuda --verbose
    - name: Run tests
      run: cargo test --features cuda --verbose

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build (CPU only)
      run: cargo build --verbose
    - name: Build (Metal)
      run: cargo build --release --features metal --verbose
    - name: Run tests
      run: cargo test --features metal --verbose
